DROP TABLE PRODUCTOS;
DROP TABLE DETALLE;
DROP TABLE CLIENTE;
DROP TABLE BOLETA;



CREATE TABLE CLIENTE ( --LA SENTENCIA CREATE TABLE ME PERMITE CREAR UNA TABLA CON LOS DATOS 
    RUT VARCHAR2(10) NOT NULL,
    NOMBRE VARCHAR2(20),
    EDAD NUMBER CHECK(EDAD>18),
    CORREO VARCHAR2(20) UNIQUE,
    TELEFONO NUMBER,
    FECHA DATE,
    DIRECCION VARCHAR2(40)
);

CREATE TABLE BOLETA(
    CODIGOBOLETA NUMBER NOT NULL,
    RUT VARCHAR2(10)NOT NULL,
    FECHA DATE,
    TOTALBOLETA NUMBER
    --PRIMARY KEY(CODIGOBOLETA),
    --FOREIGN KEY(RUT) REFERENCES CLIENTE(RUT)
);

DROP TABLE CLIENTE; --LA SENTENCIAS DROP TABLE ME PERMITE ELIMINAR UNA COLUMNA, SIN LA RECUPERACION DE LAS TABLAS NI DE LOS DATOS

ALTER TABLE CLIENTE DROP COLUMN TELEFONO; --ALTER TABLE PERMITE MODIFICAR LA TABLA EN ESTE CASO ELIMINARERMOS LA COLUMNA TELEFONO DE AQUELLA TABLA
ALTER TABLE CLIENTE ADD CELULAR NUMBER; --AGREGA LA COLUMNA DE TIPO CELULAR

ALTER TABLE CLIENTE MODIFY FECHA VARCHAR2(10); --MODIFICA LA TABLA EN EL TIPO DE DATO DE AQUELLA COLUMNA POR EJEMPLO LA FECHA CAMBIO DE TIPO DATE A VARCHAR

--CLAVE PRIMARIA , PARA UNA TABLA QUE TENGA PRIMARY KEY  DEBE POSSER LA RESTRICCCION DE "NOT NULL" COMO ES NUESTRO CASO SERA EL RUT

--LA OTRA FORMA DE DELCARAR LA PRIMARY KEY ES UTILIZANDO LA FUNCION ALTER TABLE

--PK CLIENTE REPRESENTA EL NOMBRE DE LA PK DEL CLIENTE

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(RUT);

--eliminar la tabla pk dapotada por el cliente

ALTER TABLE CLIENTE DROP CONSTRAINT PK_CLIENTE;

------------
--UNIENDO LAS FORANEAS Y LAS PRIMARIAS MEJOR A MODO PERSONAL TRABAJARLO ASI

--PK
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY(RUT);

ALTER TABLE BOLETA ADD CONSTRAINT PK_BOLETA PRIMARY KEY(CODIGOBOLETA);

--FK

ALTER TABLE BOLETA ADD CONSTRAINT FK_RUT_BOLETA FOREIGN KEY(RUT) REFERENCES CLIENTE(RUT) ON DELETE CASCADE;