--modelo a programar para este curso
/*
drop table cliente;
drop table boleta;
drop table detalle;
drop table productos;

*/


create table cliente (

    rut int not null,
    nombre VARCHAR(30),
    apellidos VARCHAR(50),
    correo VARCHAR(50),
    edad int CHECK(edad > 18)
)

CREATE table boleta (

    codigo_boleta int not NULL,
    rut int not null,
    fecha date,
    total INT
)

create table detalle (
    codigo_producto int not null,
    codigo_boleta int not null,
    cantidad int,
    total INT
)

create table productos(
    codigo_producto int not null,
    nombre VARCHAR(20),
    precio int,
    categoria VARCHAR(20)

)

--Lenguaje  de manipulacion de los datos
/*
    Lenguaje proporcionado por el gestor de base de datos para llevar a cabos tareas de consulta y manipulacion de los datos

    Siguientes sentencias

    Sentencia de insercion(Insert)
    Sentencia de modificacion(update)
    Sentenecia de eliminacion (delete)
    Sentencia de consulta (select)
*/

/*
Sentencia de insercion 
INSERT INTO NOMBRE_TABLA(COLUMNAS) VALUES(VALORES);

SELECT * FROM cliente;
insert into cliente(rut) VALUes('19104897-0');

Sentencia de Update
UPDATE NOmbre_tabla set columna1 = valor1, columna2 = valor2 where columna operator valor
*UPDATE productos SET nombre = 'NOTEBOOK LENOVO' WHERE codigo_producto = 1;

*/

--SENTENCIA DELETE
--DELETE FROM NOMBRE_TABLA WHERE COLUMNA OPERATOR VALOR

DELETE FROM productos;
select * from productos

INSERT INTO productos VALUES ('1', 'Notebook Lenovo', 380.000, 'PORTABLES')
INSERT INTO PRODUCTOS(codigo_producto,NOMBRE, PRECIO , CATEGORIA) VALUES (1,'Notebook Lenovo',380.000,'Portables');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO , CATEGORIA) VALUES(2, 'CELULAR MOTOROLA', 110.000, ' TECNOLOGIA');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE , PRECIO , CATEGORIA) VALUES (3,'AUDIFONOS MACROTEL',3.500,'AUDIO');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (4, 'NOTEBOOK SAMSUNG',500.000, 'PORTABLES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO , CATEGORIA) VALUES (5,'PANTALLA 17" AOC',67.900,'MONITORES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO , CATEGORIA) VALUES (6,'PANTALLA 21" DELL',81.900, 'MONITORES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (7,'NOTEBOOK HP',280.990,'PORTABLES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (8, 'CELULAR IPHONE 6S',560.000,'TECNOLOGIA');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (9,'CELULAR LG',450.000,'TECNOLOGIA');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (10,'MOUSE BLUETOOH',28.990,'ACCESORIOS');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO , CATEGORIA) VALUES (11,'MONITOR 17 " SAMSUNG',150.000, ' MONITORES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE , PRECIO , CATEGORIA) VALUES (12,'MONITOR 17 " LENOVO',250.000, 'MONITORES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (13, 'MONITOR 17 "LG', 125.000, 'MONITORES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE , PRECIO ,CATEGORIA) VALUES (14, 'MONITOR 15" LENOVO0',200.000, 'MONITORES');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES(16, 'MOTO G 2015',180.000,'TECNOLOGOIA');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO, CATEGORIA) VALUES (17, 'MOTO X PLAY',370.000,'TECNOLOGIA');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO , CATEGORIA) VALUES (18,'IPAN MINI 2',200.000,'TABLETS');
INSERT INTO PRODUCTOS(codigo_producto, NOMBRE, PRECIO , CATEGORIA) VALUES (19,'IPAD AIR',260.000,'TABLETS');
INSERT INTO PRODUCTOS VALUES (20,'NOTEBOOK MSI',850000,'PORTABLES');
INSERT INTO PRODUCTOS VALUES (21,'MOUSE MICROSOFT',8500,'ACCESORIOS');

SELECT * FROM productos;
delete FROM productos WHERE codigo_producto =1 and categoria = 'Portables';

/*
    funcion select la mas importante de todas , posee la mayor cantidad de operadores, funciones e instrucciones para realizar las consultas
    consultas con operadores y manejo de funciones

    Operador de compuesto

    AND Verdado si todas las condiciones por separado son VERDADERO
    VERDADERO si el operador está en el
    BETWEEN rango de comparación
    VERDADERO si la subconsulta retorna una
    EXISTS
    o más filas
    VERDADERO si el operador es igual a un
    IN
    elemento de la lista de expresiones
    VERDADERO si el operador coincide con
    LIKE
    el patrón
    Muestra el resultado si la condición NO ES
    NOT
    VERDADERA
    VERDADERO si alguna de las condiciones
    OR
    por separado es VERDADERO
*/

--operador compuesto and
SELECT * FROM productos;
SELECT NOMBRE, PRECIO FROM productos WHERE PRECIO > 1000000 and PRECIO < 200000;

--OPERADOR COMPUESTO BETWEEEN

SELECT * FROM productos;
SELECT NOMBRE , PRECIO FROM PRODUCTOS WHERE PRECIO BETWEEN 1000000 AND 200000;

--OPERADOR COMPUESTO OP
SELECT * FROM PRODUCTOS;
SELECT *  FROM productos WHERE precio > 500 OR categoria = 'TABLETS';

--OPERADOR COMPUESTO IN ¨

SELECT * FROM PRODUCTOS;
DELETE FROM productos WHERE codigo_producto = 1;
SELECT * FROM productos WHERE codigo_producto IN (1,2);


--OPERADOR COMPUESTO POR LIKE

SELECT * FROM PRODUCTOS;

SELECT * from productos where nombre LIKE 'a%';

SELECT * FROM productos WHERE categoria  LIKE '%ES';

SELECT * FROM productos WHERE nombre LIKE '%17%'

--OPERADOR COMPUESTO NOT

SELECT * from productos where not precio > 500;

SELECT * FROM productos WHERE categoria NOT LIKE '%ES';


--CONSULTA 1
--AUMENTAR EL PRECIO DE LOS PRODUCTOS EN UN 15% PARA LA CATEGOR�A 'TABLETS'

SELECT * from productos WHERE categoria = 'TABLETS';
UPDATE productos set precio = (precio + precio*0.15) where categoria = 'TABLETS';


--CONSULTA 2
--MOSTRAR EL NOMBRE Y APELLIDO DE LOS CLIENTES CONCATENADO COMO SI FUERA UN SOLO ATRIBUTO
--EJEMPLO: ALEJANDRO SEPULVEDA
SELECT * FROM CLIENTE;
SELECT CONCAT(NOMBRE , ' ', apellidos) FROM CLIENTE 

--CONSULTA 3
--MOSTRAR LOS NOMBRES DE LOS CLIENTES EN MAY�SCULA

SELECT upper(nombre) from cliente;


--CONSULTA 4
--SUPONGA QUE SE HACE UN DESCUENTO A LOS PRODUCTOS CON CATEGORIA 'TECNOLOGIA'
--MUESTRE EL NOMBRE Y PRECIO DE AQUELLOS PRODUCTOS APLICANDO 25% DE DESCUENTO AL PRECIO

select nombre , precio = (precio - precio*0.25) from productos  where categoria = 'TECNOLOGIA'

--CONSULTA 5
--MUESTRE LOS CLIENTES MENCIONANDO NOMBRE, APELLIDOS Y EDAD DONDE
--EL LARGO DEL NOMBRE SEA IGUAL A 6

SELECT NOMBRE, APELLIDOS , EDAD FROM CLIENTE WHERE LEN(nombre) = 6;

--CONSULTA 6
--MUESTRE EL NOMBRE Y CORREO DEL CLIENTE REALIZANDO LA SIGUIENTE MODIFICACI�N
--SI EL CORREO DICE UCM.CL, AHORA DEBE DECIR GMAIL.COM

select * from cliente;


--CONSULTA 7
--REALICE UNA CONSULTA QUE AGREGUE EL GUION (-) ANTES DEL �LTIMO N�MERO DE CADA RUT



--CONSULTA 8
--MUESTRE EL NOMBRE Y EDAD DE LOS CLIENTES QUE POSEAN UNA EDAD MENOR A 20 A�OS


--CONSULTA 9
--MUESTRE EL CODIGOPRODUCTO, NOMBRE Y CATEGORIA DEL PRODUCTO QUE POSEA C�DIGO 1 Y CATEGOR�A PORTABLES



--CONSULTA 10
--MUESTRA EL CODIGOPRODUCTO, NOMBRE Y CATEGORIA DEL PRODUCTO CUYA CATEGOR�A SEA PORTABLES Y TECNOLOGIA



--CONSULTA 11
--MUESTRE EL CODIGOPRODUCTO, NOMBRE, PRECIO Y CATEGORIA DE LOS PRODUCTOS 2,5,6,12,18,20 UTILIZANDO EL OPERADOR 'OR'



--CONSULTA 12
--REALICE LA MISMA CONSULTA ANTERIOR, PERO UTILIZANDO EL OPERADOR 'IN'



--CONSULTA 13
--OBTENGA EL NOMBRE, PRECIO Y CATEGORIA DE LOS PRODUCTOS CUYO PRECIO SEA MAYOR A 300000 O SU CATEGORIA SEA 'AUDIO'



--CONSULTA 14
--OBTENGA EL NOMBRE, PRECIO Y CATEGORIA DE LOS PRODUCTOS CUYO PRECIO SE ENCUENTRA ENTRE 50000 Y 100000 O CATEGORIA SEA IGUAL A 'AUDIO' O 
--EN EL NOMBRE DEL PRODUCTO DIGA 'MICROSOFT'



--CONSULTA 15
--OBTENGA RUT,NOMBRE Y APELLIDO DEL USUARIO CUYO DIGITO VERIFICADOR ES IGUAL A 3



--CONSULTA 16
--OBTENGA TODOS LOS PRODUCTOS DONDE EN EL NOMBRE APAREZCA 17"



--CONSULTA 17
--OBTENGA TODOS LOS PRODUCTOS QUE SEAN SAMSUNG O MOTOROLA



--CONSULTA 18
--OBTENGA SOLO LOS PRODUCTOS QUE NO SEAN SAMSUNG



--CONSULTA 19
--OBTENGA LOS PRODUCTOS DONDE SU CATEGORIA FINALICE CON LAS LETRAS 'ES'



--CONSULTA 20
--OBTENGA LOS PRODUCTOS QUE TENGAN UN PRECIO DE 200000 Y ADEM�S SEAN DE CATEGOR�A TABLETS



--CONSULTA 21
--OBTENGA LOS PRODUCTOS QUE SEAN NOTEBOOKS O SEAN DE LA MARCA SAMSUNG



--CONSULTA 22
--OBTENGA NOMBRE Y EL A�O DE NACIMIENTO ESTIMADO DE CADA CLIENTE CONSIDERANDO SU EDAD



--CONSULTA 23
--OBTENGA TODOS LOS PRODUCTOS QUE CON UN 75% DE DESCUENTO CUESTEN MENOS DE 50000 (DEBE MOSTRAR EL PRECIO ORIGINAL Y EL PRECIO CON EL 75% DE DESCUENTO PARA VERIFICAR)



--CONSULTA 24
--MUESTRE EL NOMBRE Y PRECIO DE LOS PRODUCTOS CUYA CODIGO DE PRODUCTO ES MAYOR A 4 Y MENOR A 14



--CONSULTA 25
--REALICE LA MISMA CONSULTA ANTERIOR CON BETWEEN (SI YA LO HIZO CON BETWEEN, H�GALO CON 'AND') PARA QUE ENTREGUE EL MISMO RESULTADO



--CONSULTA 26
--REALICE LA CONSULTA 24 PERO AHORA UTILIZANDO SOLAMENTE EL OPERADOR 'OR' PARA QUE ENTREGUE EL MISMO RESULTADO



--CONSULTA 27 (ESTO SE PONE A�N MEJOR)
--REALICE LA CONSULTA 24 PERO UTILIZANDO EL OPERADOR 'IN' PARA QUE ENTREGUE EL MISMO RESULTADO



--CONSULTA 28 (TODAV�A PUEDE SER MEJOR)
--REALICE LA CONSULTA 24 UTILIZANDO EL OPERADOR EN CONJUNTO 'NOT IN' PARA QUE ENTREGUE EL MISMO RESULTADO



--CONSULTA 29 (PORFAVOR DETENTE, NO PUEDE SEGUIR O S�?)
--REALICE LA CONSULTA 24 UTILIZANDO 'NOT BETWEEN' PARA QUE ENTREGUE EL MISMO RESULTADO



--CONSULTA 30 (HAY M�S CONSULTAS EQUIVALENTES DE DONDE SALIERON LAS ANTERIORES)
--MODIFIQUE LA CONSULTA 24 PARA QUE FUNCIONE CON EL OPERADOR 'NOT' PARA QUE ENTREGUE EL MISMO RESULTADO